ALTER TABLE TIMETABLE DROP CONSTRAINT FK_TIMETABLE_STATION_FK
ALTER TABLE TIMETABLE DROP CONSTRAINT FK_TIMETABLE_ROUTE_FK
ALTER TABLE LINE DROP CONSTRAINT FK_LINE_START_STATION_FK
ALTER TABLE LINE DROP CONSTRAINT FK_LINE_ROUTE_FK
ALTER TABLE LINE DROP CONSTRAINT FK_LINE_STOP_STATION_FK
ALTER TABLE LINE DROP CONSTRAINT UNQ_LINE_0
DROP TABLE ROUTE CASCADE CONSTRAINTS
DROP TABLE PERSON CASCADE CONSTRAINTS
DROP TABLE TIMETABLE CASCADE CONSTRAINTS
DROP TABLE STATION CASCADE CONSTRAINTS
DROP TABLE LINE CASCADE CONSTRAINTS
DROP SEQUENCE ALWARA_SEQUENCE
